from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.domain.models import DigestDashboard, DigestPublishReport, NewsItem, TextPublishResult


@runtime_checkable
class DigestRepositoryPort(Protocol):
    def reserve_new(self, items: tuple[NewsItem, ...]) -> tuple[NewsItem, ...]: ...
    def mark_result(self, item: NewsItem, result: TextPublishResult) -> None: ...
    def remember_without_publishing(self, items: tuple[NewsItem, ...]) -> None: ...
    def record_run(self, report: DigestPublishReport, trigger: str) -> None: ...
    def has_runs(self) -> bool: ...
    def dashboard(self, limit: int = 20) -> DigestDashboard: ...
